version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
